# Generated by Django 5.1.1 on 2024-09-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='username',
            new_name='email',
        ),
    ]
